version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  cooldown:
    default-days: 14
  groups:
    all:
      patterns:
      - '*'
  target-branch: master
  open-pull-requests-limit: 1
  assignees:
  - jsoehner
- package-ecosystem: docker
  directories:
  - /
  - /contrib
  schedule:
    interval: monthly
  cooldown:
    default-days: 14
  groups:
    all:
      patterns:
      - '*'
  target-branch: master
  open-pull-requests-limit: 1
  assignees:
  - jsoehner
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: cron
    cronjob: 0 0 1-7,15-21 * 1
  cooldown:
    default-days: 3
  groups:
    vuls:
      patterns:
      - github.com/MaineK00n/vuls-data-update
      - github.com/MaineK00n/vuls2
    trivy:
      patterns:
      - github.com/aquasecurity/trivy
      - github.com/aquasecurity/trivy-db
      - github.com/aquasecurity/trivy-java-db
    others:
      patterns:
      - '*'
      exclude-patterns:
      - github.com/MaineK00n/vuls-data-update
      - github.com/MaineK00n/vuls2
      - github.com/aquasecurity/trivy
      - github.com/aquasecurity/trivy-db
      - github.com/aquasecurity/trivy-java-db
  target-branch: master
  open-pull-requests-limit: 1
  assignees:
  - jsoehner
